# Generated by Django 4.0.2 on 2022-02-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=models.CharField(choices=[('IT and Networks', 'IT and Networks'), ('UI/UX', 'UI/UX'), ('Web Development', 'Web Development'), ('Devops', 'Devops')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
